### ISSUE TITLE
Provide support for BCF XML 3.0, BCF API 2.1, and BCF API 3.0

### ISSUE THREAD

**Issue by Moult** [Parametricos/BCF-js#1]
Just for the record :)

**Comment by harrycollin** [comment]
Hey @Moult, thanks for the suggestions. How would you like to see BCF API implemented? Are we simply talking about typings or a client solution?

**Comment by ngorlani** [comment]
Hi @harrycollin, will BCF-js provide support for BCF 3.0 (client side) ?
Thanks

**Comment by harrycollin** [comment]
@ngorlani definitely. I haven't had time to look into this yet, but if you're needing it now feel free to make a PR. We'll likely have to restructure the project to support additional BCF versions. If you have any thoughts on this I'd love to hear your feedback.

**Comment by harrycollin** [comment]
I'll close this for now as @nelsonhp3 recently added support for XML 2.1 & 3.0. If someone in the future needs support for BCF API I'll reopen this issue.
